spring.application.name=${NAME_DEV_TURNOS_ENFERMERIA}
spring.config.import=optional:file:./env.properties
server.port=${PORT_DEV_TURNOS_ENFERMERIA}
spring.datasource.url=${POSTGRES_DEV_DB_TURNOS_ENFERMERIA_URL}
spring.datasource.username=${POSTGRES_DEV_DB_USER}
spring.datasource.password=${POSTGRES_DEV_DB_PASSWORD_JDESARROLLO}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Eureka config
#eureka.client.enabled=true
#eureka.client.service-url.defaultZone=${SERVER_PRODUCCION}:${PORT_DEV_EUREKA_SERVER}/eureka/

security.jwt.key.private=${SECRET_KEY_PRIVATE_DEV}

# Configuración de correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_INFORMATIVO}
spring.mail.password=${PASSWORD_EMAIL_INFORMATIVO}
spring.mail.properties.debug=false
spring.mail.properties.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Configuración de la aplicación
app.mail.from=${spring.mail.username}
app.mail.enabled=true